// <auto-generated />
namespace EmployeeManagementApp.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddGUIDforemployeeid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddGUIDforemployeeid));
        
        string IMigrationMetadata.Id
        {
            get { return "201811011201551_Add GUID for employee id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
